POST http://localhost:3003/api/blogs
Content-Type: application/json 

{
    "title": "My second blog",
    "author": "John Doe",
    "url": "http://www.johndoe.com",
    "likes": 0
}
###
GET http://localhost:3003/api/blogs
###
DELETE http://localhost:3003/api/blogs/667804a2f4b2a76ebee85803